import { Outfit } from "next/font/google";
import "./globals.css";
import Header from "../Components/Header";

const outfit = Outfit({subsets: ["latin"], weight: ["400", "500","600","700"]});
export const metadata = {
  title: "Blogger",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={outfit.className}
        suppressHydrationWarning={true}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
